In [2]:
import numpy as np
x = [1,2,3,4,5,6,7]
x= np.array(x)
x.shape


(7,)

2D Array

In [ ]:
y = np.array([
    [1,2,3,4,5],
    [5,6,8,9,0],
    [0,9,8,7,6]]
)



y.shape

(3, 5)

3D Array — Stack of 2D arrays

In [ ]:
stackarray = np.array([
    [[1,2],[2,1]],
    [[6,7],[6,5]],
])
stackarray.shape
# 2 layers × 2 rows × 2 cols

(2, 2, 2)

In [21]:
stackarray = np.array([
    [[1,2],[2,1]],
    [[6,7],[6,5]],
    [[2,4,5,8,6],[3,7,9,4,2]]
])
stackarray.shape
# 2 layers × 2 rows × 2 cols

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.

In [3]:
values = np.array([2, 4, 6, 8])


In [4]:
values = values.reshape(-1,1)

In [5]:
print(values)

[[2]
 [4]
 [6]
 [8]]


In [6]:
values = values.reshape(-2,1)


In [7]:
print(values)


[[2]
 [4]
 [6]
 [8]]


In [10]:
values = values.reshape(2,2)


In [11]:
print(values)


[[2 4]
 [6 8]]


In [12]:
values = values.reshape(2,-1)

In [14]:
print(values)

[[2 4]
 [6 8]]
